@echo off
REM Double-click this file in Explorer to open the project's Storybook.
REM
REM Auto-generated by `sciter-devtools install`. This launcher lives in
REM <project>\tools\story-book\, so the project root is two levels up.
REM Paths below are overridable via environment variables.

setlocal
REM Resolve the project root (two levels up from this script) to a
REM normalized absolute path. Using %CD% avoids the trailing-backslash
REM that %~dp0 carries — a trailing \" would escape the closing quote and
REM swallow the rest of the --project argument (window never opens).
pushd "%~dp0..\.."
set "PROJECT_DIR=%CD%"
popd
if "%SCITER_DEVTOOLS_PYTHON%"=="" set "SCITER_DEVTOOLS_PYTHON=C:\Users\MPoskannyi.KH-AVQ-LP70\.claude\plugins\cache\frontend-toolkit\component-creator\0.7.78\skills\sciter-create-component\sciter-devtools\.venv\Scripts\python.exe"
if "%SCITER_DEVTOOLS_PATH%"=="" set "SCITER_DEVTOOLS_PATH=C:\Users\MPoskannyi.KH-AVQ-LP70\.claude\plugins\cache\frontend-toolkit\component-creator\0.7.78\skills\sciter-create-component\sciter-devtools\src"

if not exist "%SCITER_DEVTOOLS_PATH%" (
  echo Error: sciter-devtools not found at %SCITER_DEVTOOLS_PATH%
  pause
  exit /b 1
)

set "PYTHONPATH=%SCITER_DEVTOOLS_PATH%"
"%SCITER_DEVTOOLS_PYTHON%" -m sciter_devtools storybook --project "%PROJECT_DIR%"
if errorlevel 1 (
  echo.
  echo Storybook failed to launch ^(exit %errorlevel%^) - see the error above.
  pause
)
