// res/shared/dialogs/MessageBox/MessageBox.js
// Generated by component-creator v0.7.78 / sciter-create-page (dialog archetype, wave 2).
// Figma: file 2jGq5p5qY4lsf5QK2stfOY — placed instance 13043:1667 (512x430), component master
// 13034:20523 ("MessageBox").
//
// File shape: single-export-inline per the seeded dialog convention (dialog_idioms family
// "modalWindow" in .claude/state/frontend-analysis.json + reference-page-scaffold.md § Dialog
// file-shape): ONE Show<Name> factory export; the body lives module-local and is deliberately
// NOT exported. Named export (not default) per .claude/rules/code-style.md ("avoid default
// exports") — noted divergence from the seed's `factory_export: "default"` field.
//
// Mechanism: modal-window (toolkit reference-sciter-dialogs.md §A) — a real OS window via
// Window.this.modal(vnode), dismissed from inside with Window.this.close([value]) (§C; the
// seeded dialog_idioms.dismiss.close_path). Focus is native to the window boundary — no in-DOM
// focus trap (§Focus).
//
// Styling: MessageBox.css#message-box styleset — tokens from res/shared/lib/tokens.css, type
// via typography.css mixins (see .claude/docs/reference-styling-flow.md).

import { PrimaryButton } from "../../components/PrimaryButton/PrimaryButton.js";

/**
 * @typedef {Object} MessageBoxProps
 * @property {string} [documentName] Name of the protected document; when absent the title
 *   renders the design's verbatim placeholder text (previews/SSIM rely on it).
 */

/**
 * Dialog body. Exported for exactly ONE consumer besides this module: the dialog window
 * document (MessageBox.htm), which mounts it with `Window.this.parameters` as props — the
 * SDK-documented custom-dialog shape (docs/md/DOM/Window.md § modal({params}): modal(vnode)
 * is reserved for the predefined <info>/<alert>/<error>/<question> boxes and comes up
 * collapsed for arbitrary vnodes). App code must keep calling the ShowMessageBox factory.
 * Static composition: the password field, CAPS/eye affordances, and checkbox are non-interactive
 * placeholders per the build contract; only dismissal is wired.
 */
export class MessageBoxBody extends Element {

  /** @type {MessageBoxProps} */
  props = {};

  /** @param {MessageBoxProps} [props] */
  constructor(props = {}) {
    super();
    this.props = props ?? {};
  }

  render() {
    return (
      <div class="message-box" styleset={__DIR__ + "MessageBox.css#message-box"}>
        <div id="close" class="message-box__close" role="button" title="Close" />
        <div id="content" class="message-box__content">
          <div id="icon-row" class="message-box__icon-row">
            <div class="message-box__info-icon" />
          </div>
          <div id="title" class="message-box__title">
            {this.props.documentName
              ? "Document " + this.props.documentName + " is protected"
              : ["Document [document name.pdf] is protected", <br/>, "Poppins 18/Auto, Semi-Bold, #171D26"]}
          </div>
          <div id="field-label" class="message-box__field-label">Please enter a document owner password</div>
          <div id="field" class="message-box__field">
            <div class="message-box__field-text">Add field text here</div>
            <div class="message-box__field-right">
              <div class="message-box__caps">CAPS</div>
              <div class="message-box__eye" />
            </div>
          </div>
          <div id="checkbox-row" class="message-box__checkbox-row">
            <div class="message-box__checkbox" />
            <div class="message-box__checkbox-text">This is an example of checkbox placement</div>
          </div>
          <div id="ctas" class="message-box__ctas">
            <div id="cancel" class="message-box__cancel" role="button">
              <div class="message-box__cancel-label">Cancel</div>
            </div>
            <div class="message-box__ok">
              <PrimaryButton label="Ok" />
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Dismissal — the dialog window closes itself handing back a value (SDK §C; seeded
  // dialog_idioms.dismiss.close_path = Window.this.close([value])). Inside MessageBox.htm
  // `Window.this` is the DIALOG window, so this returns the value to the modal() caller.
  ["on click at .message-box__close"]() { Window.this.close(); return true; }
  ["on click at .message-box__cancel"]() { Window.this.close("cancel"); return true; }
  // PrimaryButton (click-stub tier) bubbles "button-press"; the only instance here is "Ok".
  ["on button-press"]() { Window.this.close("ok"); return true; }
}

/**
 * Show the MessageBox dialog modally; returns the close value
 * (`"ok"` | `"cancel"` | `undefined` for the caption ✕).
 *
 * SDK-documented custom-dialog shape (docs/md/DOM/Window.md § modal({params})): the dialog is
 * a real window document (MessageBox.htm — its root `window-*` attributes carry size 512×430dip
 * and `window-alignment="-5"` = centered against the parent window); props travel in as
 * `parameters` and come back as the Window.this.close(value) result. The modal(vnode) overload
 * is NOT used — it is reserved for the predefined <info>/<alert>/<error>/<question> boxes and
 * renders an arbitrary vnode as a collapsed window (verified on this engine).
 *
 * The scrim/backdrop over the parent is the CALLER's page layer (Home's "dialog" view state) —
 * a modal window does not dim its parent by itself.
 *
 * @param {MessageBoxProps} [props]
 * @returns {any} the Window.this.close(value) result
 */
export function ShowMessageBox(props = {}) {
  // Headless-harness path (preview/storybook/SSIM): the root preview shim
  // (res/.sdt-preview-shim.js) sets __SDT_PREVIEW__ and the body vnode is handed back for
  // inline mount — a real modal window would block the capture. Never true in the running app.
  if (globalThis.__SDT_PREVIEW__) return JSX(MessageBoxBody, props, []);
  return Window.this.modal({ url: __DIR__ + "MessageBox.htm", parameters: props });
}
