// res/shared/components/SortBy/SortBy.js
// Generated by component-creator v0.7.78 / sciter-create-component.
// Figma: file 2jGq5p5qY4lsf5QK2stfOY, node 3851:39434 ("State=Default" — dropdown field, 150x40).
// Icon pattern: static SVG file assets under img/ (fetched from the design by the asset worker;
// baked design colors, not host-tinted). See .claude/docs/reference-icon-connection.md (seed).
// Styling: SortBy.css#sort-by styleset — tokens from res/shared/lib/tokens.css, type via
// @font-sm-medium from res/shared/lib/typography.css (see .claude/docs/reference-styling-flow.md).

/**
 * @typedef {Object} SortByProps
 * @property {string} [label] Field label; defaults to "Sort by".
 */

export class SortBy extends Element {

  /** @type {string} */
  label;

  /**
   * @param {SortByProps} [props]
   */
  constructor(props = {}) {
    super();
    this.label = props?.label ?? "Sort by";
  }

  render() {
    return (
      <div class="sort-by" styleset={__DIR__ + "SortBy.css#sort-by"}>
        <div id="content" class="sort-by__content">
          <img id="sort-by" class="sort-by__icon" src={__DIR__ + "img/sort-by.svg"} />
          <span id="sort-by-2" class="sort-by__label">{this.label}</span>
        </div>
        <img id="arrows" class="sort-by__chevron" src={__DIR__ + "img/chevron-down.svg"} />
      </div>
    );
  }

  // Interactivity tier: click-stub — no dropdown is implemented in this build. The field
  // announces intent to the host via a bubbling custom event; a future build owns the popover.
  ["on click"](evt) {
    this.dispatchEvent(new Event("sortby-click", { bubbles: true, data: { label: this.label } }));
    return true;
  }
}
