// res/shared/components/PrimaryButton/PrimaryButton.js
// Generated by component-creator v0.7.78 / sciter-create-component.
// Figma: file 2jGq5p5qY4lsf5QK2stfOY, node 2371:7625 ("Size=40, State=Default, Icons=No Icon",
// 200x40 — the COMPONENT master; identity pre-resolved by the page orchestrator).
// Styling: PrimaryButton.css#primary-button styleset — tokens from res/shared/lib/tokens.css,
// type via @font-sm-medium from res/shared/lib/typography.css (typography.css must be loaded at
// document level by the hosting page; see .claude/docs/reference-styling-flow.md).

/**
 * @typedef {Object} PrimaryButtonProps
 * @property {string} label Button caption (single line, centered).
 */

export class PrimaryButton extends Element {

  /** @type {string} */
  label;

  /**
   * @param {PrimaryButtonProps} [props]
   */
  constructor(props = {}) {
    super();
    this.label = props?.label ?? "";
  }

  render() {
    return (
      <div class="primary-button" styleset={__DIR__ + "PrimaryButton.css#primary-button"}>
        <div id="icon-text" class="primary-button__icon-text">
          <div id="label" class="primary-button__label">
            <span id="area-snapshot" class="primary-button__text">{this.label}</span>
          </div>
        </div>
      </div>
    );
  }

  // Interactivity tier: click-stub — announces the press to the host via a bubbling custom
  // event; no real behavior lives here (the consuming view owns the action).
  ["on click"](evt) {
    this.dispatchEvent(new Event("button-press", { bubbles: true, data: { label: this.label } }));
    return true;
  }
}
